title:        API Vulnerabilities
url:          http://vulnerabilities.apievangelist.com
logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-logo-api-vulnerabilities.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/blog/page:num"

org: api-evangelist
repo: vulnerabilities

# Masthead title
masthead_link: http://vulnerabilities.apievangelist.com
masthead_font_size: 90
masthead_title: '{"API Vulnerabilities"}'

# Feature
feature_title: API Guide
feature_link: http://apievangelist.com
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/api-guides-loading.jpg
feature_image_width: 45

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-vulnerabilities.png
project_summary: This is my research to better understand the types of vulnerabilities being discovered out there. Not everything listed here is directly API related, but I think the wider understand helps my work in this area. Right now it is mostly curated news, but will be expanding information as I have time.

# Navigation
navigation:
  - label1: Home
    link1: /
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Blog
    link1: /blog/
    size1: 80
    extend: 1
    label2: RSS
    link2: /blog.xml
    size2: 60
    padding: 0
    decorate: 0
  - label1: News
    link1: /news/
    size1: 80
    extend: 1
    label2: RSS
    link2: /news.xml
    size2: 60
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 0
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60

# curated
curated_desc: As I keep track on the world of APIs I curate news, blog posts, articles, and other research that I feel is relevant specifically to API vulnerabilities--these are the links I am including in my research.

# organizations
org_desc: As I keep track on the world of APIs and read through the information I am curating I keep an eye out for any company, institution, or other agency that is doing anything interesting with API vulnerabilities. These are the organizations I'm currently including in my API vulnerabilities research.

# tools
tools_desc: These are the open source management related tooling that I am tracking on as part of my research, and can be used as part of the API vulnerabilities process.
